# Generated by Django 4.2.16 on 2024-11-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0002_solicitudcontacto_mensajeapoderado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaUtiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
