# Generated by Django 4.2.16 on 2024-11-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0003_listautiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='niño',
            name='apellido',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='apellido_materno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='niño',
            name='apellido_materno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='niño',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
