# Generated by Django 4.2.16 on 2024-11-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0004_remove_apoderado_apellido_remove_niño_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='contraseña',
            field=models.CharField(default='contraseña_predeterminada', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
