# Generated by Django 4.2.16 on 2024-11-19 03:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0005_apoderado_contraseña_alter_apoderado_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='titulo',
            new_name='lugar',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nombre',
            field=models.CharField(default=datetime.time(12, 0), max_length=200),
            preserve_default=False,
        ),
    ]
