# Generated by Django 4.2.16 on 2024-11-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0006_rename_titulo_evento_lugar_remove_evento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcontacto',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Visto', 'Visto')], default='Pendiente', max_length=10),
        ),
    ]
