# Generated by Django 4.2.16 on 2024-11-19 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardin_app', '0007_solicitudcontacto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='user',
            field=models.ForeignKey(
                default=1,  # Asigna un ID válido
                on_delete=models.CASCADE,
                to='auth.User',
            ),
        )
    ]
