# Generated by Django 4.2.16 on 2024-11-19 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jardin_app', '0009_alter_apoderado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoderado',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
