# Generated by Django 4.2.16 on 2024-11-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jardin_app', '0012_alter_apoderado_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='user',
        ),
    ]
